name: GitHub Profile Summary Cards

on:
  schedule:
    # Every day at 08:15 AM IST
    - cron: "45 2 * * *"

  workflow_dispatch:

concurrency:
  group: profile-summary-cards
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  summary-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

        with:
          USERNAME: shaurya1606